# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Docker Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run unit tests
      run: pytest
      
    - name: Static Code Analysis and Formatting
      run:  find . -name "*.py" | xargs black

#     - name: Log in to DockerHub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#     - name: Build Docker image
#       run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/image-name:${{ github.sha }} .

#     - name: Tag Docker image as latest
#       run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/image-name:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/image-name:latest

#     - name: Push Docker image
#       run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/image-name
      
#     - name: Deploy Docker container
#       run: docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/image-name:latest
